### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by kparal** [nitipit/markdo#2]
Please publish your tool on PyPI:
http://pypi.python.org/pypi

That will allow people to easily install it using "pip install markdo" or "easy_install markdo".

It will also handle updates and uninstalls.

Thanks!

**Comment by nitipit** [comment]
yep, I'll do that :) .

**Comment by nitipit** [comment]
Will do some code re-factor before publish on PyPI :)

**Comment by nitipit** [comment]
published > http://pypi.python.org/pypi/MarkDo/0.1
:)
