### ISSUE TITLE
ImportError: No module named appkit

### ISSUE THREAD

**Issue by kparal** [nitipit/markdo#3]
```
$ pip-python install MarkDo
Downloading/unpacking MarkDo
  Downloading MarkDo-0.2.tar.gz (274Kb): 274Kb downloaded
  Running setup.py egg_info for package MarkDo

Installing collected packages: MarkDo
  Running setup.py install for MarkDo
    changing mode of build/scripts-2.7/markdo from 664 to 775

    changing mode of /home/kparal/.local/bin/markdo to 775
Successfully installed MarkDo
Cleaning up...
$ markdo
Traceback (most recent call last):
  File "/home/kparal/.local/bin/markdo", line 3, in <module>
    from markdo.markdo import app
  File "/home/kparal/.local/lib/python/markdo/markdo.py", line 3, in <module>
    from appkit import App
ImportError: No module named appkit
```

I have no idea where `appkit` module comes from. But you could set it as a dependency in your `setup.py` and `pip` will install it automatically.

**Comment by nitipit** [comment]
Thanks.
I think it works now, I've checked on my pc.

```
$ sudo pip-python install markdo
```

I've just start publishing module on PyPI, and I'm a bit confused about how to make setup.py script and how to use PyPI website :)

**Comment by nitipit** [comment]
@kparal  FYI, AppKit is some code that has been split out from MarkDo 0.1 .., 
I think it would be good if I can make it to be an application framework on Gnome
and I would like to make more applications :)
sorry if that confuse you

**Comment by kparal** [comment]
Works now:

```
$ pip-python install MarkDo
Downloading/unpacking MarkDo
  Downloading MarkDo-0.2.1.tar.gz (275Kb): 275Kb downloaded
  Running setup.py egg_info for package MarkDo

Downloading/unpacking appkit==0.2 (from MarkDo)
  Downloading AppKit-0.2.tar.gz
  Running setup.py egg_info for package appkit

Requirement already satisfied (use --upgrade to upgrade): Jinja2 in /usr/lib/python2.7/site-packages (from MarkDo)
Installing collected packages: MarkDo, appkit
  Running setup.py install for MarkDo
    changing mode of build/scripts-2.7/markdo from 664 to 775

    changing mode of /home/kparal/.local/bin/markdo to 775
  Running setup.py install for appkit

Successfully installed MarkDo appkit
Cleaning up...
```

Also starts OK. Thanks!

**Comment by kparal** [comment]
Now I need some similar tool for RST :-)

**Comment by nitipit** [comment]
How do u know that :P ?

**Comment by nitipit** [comment]
@kparal 
here u go :) https://github.com/nitipit/restr

**Comment by kparal** [comment]
Perfect! Thanks. Maybe MarkDo and Restr could be a single tool handling both formats (depending on file suffix)? But that's just an idea, I'm completely satisfied with two tools as well.

**Comment by nitipit** [comment]
yeah, maybe, but I don't have any intention to combine them right now..
the hardest part could be the name of the editor :D
