### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by jean-io** [nitipit/markdo#8]
Fail to install with both `pip` and `easy_insatll`

**easy_install error:**

```
Writing /tmp/easy_install-0ykGy2/pygobject-2.28.3/setup.cfg
Running pygobject-2.28.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0ykGy2/pygobject-2.28.3/egg-dist-tmp-JbQ79w
error: Setup script exited with 
********************************************************************
* Building PyGObject using distutils is only supported on windows. *
* To build PyGObject in a supported way, read the INSTALL file.    *
********************************************************************
```

**pip error:**

```
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pygobject
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/dist-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pygobject
```

I am running on Debian 7 with Gnome 3 and both py 2 and py 3 installed. Py 2.7.3 is the default version.

I hope it will be easy to fix :)

**Comment by nitipit** [comment]
@Ricain I think you have to install `pygobject3` as a dependency.

**Comment by jean-io** [comment]
@nitipit I installed `python3-gi` with `apt-get` ([source](https://wiki.gnome.org/action/show/Projects/PyGObject)) but still stuck with the same error.

This does not come from your app, right?

**Comment by nitipit** [comment]
@Ricain
- It works fine for me, fedora 20, python 2.7, both from 'pypi' or from this 'git repository' master branch
- This app can't run with python 3.x yet. (Due to [appkit](https://github.com/nitipit/appkit) <= v0.2.8)
- I think the error occurs when it try to build pygobject (with python2.7 as it said from traceback) , python3-gi installed doesn't help

Try to install `pygobject2` : "Python 2 bindings for GObject Introspection", not sure how it's named in Debian.
Please send me the full command that you've used to install.

**Comment by jean-io** [comment]
@nitipit 

Here is the installation command for pygobject2

```
# apt-get install python-gi
```

[package details](https://packages.debian.org/wheezy/python-gi)
But the strange thing is that the package is already installed by default.

To install your app, I simply used:

```
# pip install markdo
```

**Comment by nitipit** [comment]
@Ricain
Hmm, I guess it's about dependency name in `setup.py` that might not work with debian, let me check :9

**Comment by nitipit** [comment]
@Ricain , It's about `python-gobject` name in `setup.py` from `AppKit` package (Markdo's dependency) that make `Markdo` doesn't work in debian.
I found the solution to fix it but it could take some time to release (To easily install by `pip`).

**Comment by nitipit** [comment]
@Ricain , You can just install `appkit` from github for now and see if it works :9

```
pip install -e git+https://github.com/nitipit/appkit.git#egg=appkit
pip install markdo
```

**Comment by jean-io** [comment]
I am sorry, I quitted my work computer with Debian... I can't tell you if this issue is still there or if you fixed it.
